name: Grade Assignment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas matplotlib seaborn nbformat nbconvert jupyter_client ipykernel

      - name: Verify installed Jupyter kernels
        run: |
          python -m ipykernel install --user --name=python3
          jupyter kernelspec list

      - name: Run tests and calculate grade
        run: |
          # Run the tests
          python -m unittest discover -s tests -p "test_*.py" > result.log

          # Extract the test result from the log file
          GRADE=$(python -c "
          import unittest
          from climate_data import TestClimateEDA
          import re

          with open('result.log', 'r') as file:
            result = file.read()

          test_suite = unittest.defaultTestLoader.loadTestsFromTestCase(TestClimateEDA)
          test_runner = unittest.TextTestRunner()
          test_result = test_runner.run(test_suite)

          total_tests = test_result.testsRun
          failed_tests = len(test_result.failures) + len(test_result.errors)
          passed_tests = total_tests - failed_tests
          grade = (passed_tests / total_tests) * 100 if total_tests > 0 else 0
          print(round(grade))
          ")
          echo "Grade: $GRADE/100"
          echo "GRADE=$GRADE" >> $GITHUB_ENV

      - name: Create grade summary
        run: |
          echo "## Assignment Grade: $GRADE/100" > grade_summary.md

      - name: Upload grade summary
        uses: actions/upload-artifact@v4
        with:
          name: grade-summary
          path: grade_summary.md

  

